#!/bin/bash

#this script creates statistics file named 'stats_delta.txt'

# stats fields:
# level file_name file_source_size file_compressed_size decompression_time decompression_ratio


let b=1 # block_size between 1 to 8 bytes

while [ $b -le 8 ]; do  # go over all block sizes


	let i=1

	while [ $i -le $1 ]; do # scan all files

		cd ..
		cd packet_files
	
		packets_record=( `ls -l | grep packets_100k_1_1_arr_$i.bin` )
		packets_size=${packets_record[4]}

		cd ..
		cd delta_encoding


	
		# compression
		./delta_encoding_v2 -e ../packet_files/packets_100k_1_1_arr_$i.bin compressed$i_$b.bin 100000 $b

		compressed_record=( `ls -l | grep compressed$i_$b.bin` )
		compressed_size=${compressed_record[4]}


		path="../stats_delta_v2/stats_delta_v2_1_1.txt"

		echo -n -e "$packets_size\t" >> $path	
		echo -n -e "$compressed_size\t" >> $path
		echo -n -e "$b\t" >> $path
		echo "" >> $path

	
		rm -f compressed$i_$b.bin
		

		echo "i=$i    b=$b"
		let i=i+1

	

	done

	let b=b+1


done
	

